name: visibility_cached_image
description: |
  A Flutter package that efficiently handles loading both network and asset images with advanced memory management techniques.

version: 0.0.2
homepage: https://github.com/mustafa-707/visibility_cached_image
repository: https://github.com/mustafa-707/visibility_cached_image
issue_tracker: https://github.com/mustafa-707/visibility_cached_image/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  hive_ce_flutter: ^2.1.0
  uuid: ^4.5.1
  dio: ^5.7.0
  flutter_hooks: ^0.20.5
  async: ^2.12.0

dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
